// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneBookWeb.Databases;

#nullable disable

namespace PhoneBookWeb.Migrations
{
    [DbContext(typeof(ContactDbContext))]
    [Migration("20220417162239_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PhoneBookWeb.Databases.Contacts.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("f_address");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("f_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("f_name");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("varchar(11)")
                        .HasColumnName("f_phone_no");

                    b.HasKey("Id");

                    b.ToTable("t_contact");
                });
#pragma warning restore 612, 618
        }
    }
}
